=== Lizbetta of Eyselaan

AKA Betty, Blackheart Betty

Born in 1240

* *1251* + 
My happiest memories are also my earliest. I was a cheerful youngling, unruly and hellbent from the call of grandad's cockerels till the fall of the star-filled vail. Father practically egged on my constant larks. He was the chief bodyguard of Count Viston Lauretton-de-Truane, a demanding job that often felt like a gaol sentence. I think seeing me living a life of complete freedom sated his own hunger to be carefree.
+
When he saw me playing with a sword, he was at first amused; none of my elder brothers had taken any interest in the soldiering arts. Soon his amusement turned into a kind of prideful glee. "Betty, you've some fire in your belly, unlike your brothers. If you work hard, I'll teach you how to fight. Just don't tell your mother!"
+
He taught me well. Maybe too well. 

* *1255* + 
Father accompanied Count Viston on a mission to Kaedwen under the direct order of King Videmont. It would be an endless run of peace talks and diplomatic horsetrading. Father convinced mother that the long trip would be both dull and safe trip, so the whole family went along as part of the Lauretton-de-Truane retinue.

* *1256* +
Sneaking across the rooftops of Ban Gleann, I spied a noble lady running from two robbers. I lobbed a couple of roof tiles at the robbers, which almost cleaved one of their skulls. Startled, they ran off. The noble lady beckoned me down. It proved to be none other than an extremely grateful Countess Lauretton-de-Truane. For the month that followed, I was her near-constant companion. She insisted that I be given the post of bodyguard. Father wasn't as pleased as I thought he would be. Apparently, it was all fine and well for me to hack away at training dummies but quite another thing altogether to be in the service of the Count and Countess. While father showed me how to thrust and parry, the Countess taught me the importance of good composure, and the value from striking from afar. When I showed interest in improving my archery skills, she had me train daily with King Henselt's elite Dun Banner cavarlymen. I became proficient on a horse and a could shoot as well as any of the Dun Banner regulars, who started to treat me as a bit of a mascot. I loved it, and apparently my galavanting around Kaedwen's finest soldiers had briefly raised suspicions that I was spying for Aedirn. Such an accusation apparently raised howls of laughter from the Kaedweni court, much to everyone's relief.

* *1257* +
A fracas between Aedirnian and Kaedweni border guards brought our mission to an end. The family's return to Aedirn's warmer climate was a bit of a relief but I really missed life in Ban Gleann. The failure of the mission had left Count in a foul mood. Father was constantly being sent away on erands. The Countess



Yaevinn
