=== Lizbetta of Eyselaan

AKA Betty, Blackhearted Betty

.Siblings
|=======================
|**Name (Current age)** |**Gender**  |**Feelings** |**Demeaner**
|Luan (40)    |Male |No feelings     |Agressive
|Duncan (39)   |Male |No feelings     |Depressive
|Vivenda (37)    |Female     |No feelings |Depressive
|Aerial (29) |Female | No feelings   |Strange
|Dreric (27) |Male |Wants you dead |Immature
|Lyra (22)|Female| Possessive |Talkative
|Abron(20) |Male| Looks up to you |Romantic
|=======================

Born in 1240

* *1251* + 
My happiest memories are also my earliest. I was a cheerful youngling, unruly and hellbent from the call of grandad's cockerels till the fall of the star-filled vail. Father practically egged on my constant larks. He was the chief bodyguard of Count Viston Lauretton-de-Truane, a demanding job that often felt like a gaol sentence. I think seeing me living a life of complete freedom sated his own hunger to be carefree.
+
When he saw me playing with a sword, he was at first amused; none of my elder brothers had taken any interest in the soldiering arts. Soon his amusement turned into a kind of prideful glee. "Betty, you've some fire in your belly, unlike your brothers. If you work hard, I'll teach you how to fight. Just don't tell your mother!"
+
He taught me well. Maybe too well. 

* *1255* + 
Father accompanied Count Viston on a mission to Kaedwen under the direct order of King Videmont. It would be an endless run of peace talks and diplomatic horsetrading. Father convinced mother that the long trip would be both dull and safe, so the whole family went along as part of the Lauretton-de-Truane retinue.

* *1256* +
Sneaking across the rooftops of Ban Gleann, I spied a noble lady running from two robbers. I lobbed a couple of roof tiles at the robbers, which almost cleaved one of their skulls. Startled, they ran off. The noble lady beckoned me down. It proved to be none other than an extremely grateful Countess Lauretton-de-Truane. For the month that followed, I was her near-constant companion. She insisted that I be given the post of bodyguard. Father wasn't as pleased as I thought he would be. Apparently, it was all fine and well for me to hack away at training dummies but quite another thing altogether to be in the service of the Count and Countess. While father showed me how to thrust and parry, the Countess taught me the importance of good composure, and the value from striking from afar. When I showed interest in improving my archery skills, she had me train daily with King Henselt's elite Dun Banner cavarlymen. I became proficient on a horse and a could shoot as well as any of the Dun Banner regulars, who started to treat me as a bit of a mascot. I loved it, and apparently my galavanting around Kaedwen's finest soldiers had briefly raised suspicions that I was spying for Aedirn. Such an accusation apparently raised howls of laughter from the Kaedweni court, much to everyone's relief.

* *1257* +
A fracas between Aedirnian and Kaedweni border guards brought our mission to an end. The family's return to Aedirn's warmer climate was a bit of a relief but I really missed life in Ban Gleann. The failure of the mission had left Count very much out-of-favour with the king which set him in perminent foul mood. The king was forever sending the Count on thankless erands, and father with him. By winter, the Countess had made the decision to spend time with her family in Gulet. In our last meeting she expressed worries for the kingdom, the royal family and for me. She gave me a precious silver ring as a token of our friendship but bid me to wear it on a pendant. She said it would not be looked on favourably by court. On all counts, her words rung very true. Weeks later, news of the death of the countess arrived from Vengeburg. Bandits or, as some suspected, a Kaedweni insurgent group drove her carriage off the road, during her journey to hr fa

* *1258* +
Someone at court notices that the ring I wear around my neck belonged to the Countess. I'm arrested and thrown in gaol. Father is forced to step down as the Count's chief bodyguard, a demotion that he had been yearning for years. However, my young brother Dreric lost his commission to the royal guard. His life's dream, dragged away from him. He never forgave me. Soon after Dreric fell in with a small mercenary company.  Other than Dreric's loss, the incident was resolved in a matter of days when the lady-in-waiting for the late Countess produces an official record of the gift. The matter would have been quickly forgotten had I not confronted my accuser and left them blooded and beaten. A commoner beating a young noble could easily been my end, but my father's good standing and my wrongful imprisonment saved me. I was to be exciled from home for 5 years. In which time I was to server as bodyguard to Shaya Montague, a sorcerous assisting 

* *1260* +

* *1271* Play begins

Yaevinn
