=== Lizbetta of Eyselaan

AKA Betty, Blackhearted Betty

.Siblings
|=======================
|**Name (Current age)** |**Gender**  |**Feelings** |**Demeaner**
|Luan (40)    |Male |No feelings     |Agressive
|Duncan (39)   |Male |No feelings     |Depressive
|Vivenda (37)    |Female     |No feelings |Depressive
|Aerial (29) |Female | No feelings   |Strange
|Dreric (27) |Male |Wants you dead |Immature
|Lyra (22)|Female| Possessive |Talkative
|Abron(20) |Male| Looks up to you |Romantic
|=======================

Born in 1240

* *1251* + 
My happiest memories are also my earliest. I was a cheerful youngling, unruly and hellbent from the call of grandad's cockerels till the fall of the star-filled vail. Father practically egged on my constant larks. He was the chief bodyguard of Count Viston Lauretton-de-Truane, a demanding job that often felt like a gaol sentence. I think seeing me living a life of complete freedom sated his own hunger to be carefree.
+
When he saw me playing with a sword, he was at first amused; none of my elder brothers had taken any interest in the soldiering arts. Soon his amusement turned into a kind of prideful glee. "Betty, you've some fire in your belly, unlike your brothers. If you work hard, I'll teach you how to fight. Just don't tell your mother!"
+
He taught me well. Maybe too well. 

* *1255* + 
Father accompanied Count Viston on a mission to Kaedwen under the direct order of King Videmont. It would be an endless run of peace talks and diplomatic horsetrading. Father convinced mother that the long trip would be both dull and safe, so the whole family went along as part of the Lauretton-de-Truane retinue.

* *1256* +
Sneaking across the rooftops of Ban Gleann, I spied a noble lady running from two robbers. I lobbed a couple of roof tiles at the robbers, which almost cleaved one of their skulls. Startled, they ran off. The noble lady beckoned me down. It proved to be none other than an extremely grateful Countess Lauretton-de-Truane. For the month that followed, I was her near-constant companion. She insisted that I be given the post of bodyguard. Father wasn't as pleased as I thought he would be. Apparently, it was all fine and well for me to hack away at training dummies but quite another thing altogether to be in the service of the Count and Countess. While father showed me how to thrust and parry, the Countess taught me the importance of good composure, and the value from striking from afar. When I showed interest in improving my archery skills, she had me train daily with King Henselt's elite Dun Banner cavarlymen. I became proficient on a horse and a could shoot as well as any of the Dun Banner regulars, who started to treat me as a bit of a mascot. I loved it, and apparently my galavanting around Kaedwen's finest soldiers had briefly raised suspicions that I was spying for Aedirn. Such an accusation apparently raised howls of laughter from the Kaedweni court, much to everyone's relief.

* *1257* +
A fracas between Aedirnian and Kaedweni border guards brought our mission to an end. The family's return to Aedirn's warmer climate was a bit of a relief but I really missed life in Ban Gleann. The failure of the mission had left Count very much out-of-favour with the king which set him in perminent foul mood. The king was forever sending the Count on thankless erands, and father with him. By winter, the Countess had made the decision to spend time with her family in Gulet. In our last meeting she expressed worries for the kingdom, the royal family and for me. She gave me a precious silver ring as a token of our friendship but bid me to wear it on a pendant. She said it would not be looked on favourably by court. On all counts, her words rung very true. Weeks later, news of the death of the countess arrived from Vengeburg. Bandits or, as some suspected, a Kaedweni insurgent group drove her carriage off the road, during her journey to hr fa

* *1258* +
Someone at court notices that the ring I wear around my neck belonged to the Countess. I'm arrested and thrown in gaol. Father is forced to step down as the Count's chief bodyguard, a demotion that he had been yearning for years. However, my young brother Dreric lost his commission to the royal guard. His life's dream, dragged away from him. He never forgave me. Soon after Dreric fell in with a small mercenary company.  Other than Dreric's loss, the incident was resolved in a matter of days when the lady-in-waiting for the late Countess produces an official record of the gift. The matter would have been quickly forgotten had I not confronted my accuser and left them blooded and beaten. A commoner beating a young noble could easily been my end, but my father's good standing and my wrongful imprisonment saved me. I was to be exciled from home for 5 years. In which time I was to server as bodyguard to Shaya Montague, a sorcerous assisting King Demavend III.
+
Shaya is thrilling. There is chemistry between us, but there is something about her that soon starts to repel me. We travel to Upper Aedirn, close to Ban Gleann. I'm excited to be back in this place, but also uneasy. Shaya's daily efforts seem true to Demavend's orders, but the whole canvas is off somehow. Shaya has a hidden agenda, but exactly what eludes me. I am wary to press the matter. I can hear whispered warnings from the Countess, "Play the game, Betty. Show no tell, play along." Shaya's good word is the only way I'll get home, so I remain constant and loyal. In late summer Shaya attempts to seduce me. My initial feelings of excitement had long given way to apprehension, her attempt fails. Shaya is a woman not accustomed to rejection,so things go very badly, in that "running for your life with a homocidal sorceress hot on your heels" way. 

* *1260* +
I work as a sell sword in Dol Blarhanna and then Posada. I joke that Shaya has driven me to the edge of the world, but at night I huddle in the dark alone and cry myself to sleep. On my 20th birthday I get drunk, sleep with two separate mercenaries and climb one of Posada's pinnacles, briefly contemplating a leap off. Instead, I tumble into a tiny cave hidden to anyone not clambering up the pinnacle's eastern side. The cave is painted with strange symbols. I feel the energy of the spheres, but I am too drunk to feel the appropriate level of terror. Instead I fall into a deep sleep and dream of all of the Northern kingdoms set alight. I see a mist and the flash of black and gold. Then flame and smoke surrounds me. It's the choking smell of ash that wakes me. This was a strange awakening. I feel a calm like none before. I should be painfully hungover but I feel focused, like the instant before a hunters killshot. A vision of my world burning should leave me deeply disturbed, but instead I feel liberated. On reflection, that feeling was like escaping a dark prison cell only to find myself in a fearce snowstorm.

Geralt is 100 years old.

* *1261* +
I make a terrible misjudgement. 
My vision in the cave haunts me any night after I've been drinking. I go through periods of not boozing, until the thirst for a good wine overrides my inclinations to escape the dream. I decide that I must tell my father about my vision. He is the only living person I feel anything for, the one person in the world I want to save from this fate. He was the only person who tried to stand up for me during my brief imprisonment, I will not let him burn. I sneak into Eysenlaan, if caught I'll face imprisonment but I am not afraid anymore, not of anything. It costs me so much. 

I found father teaching sword to recruits at the Count's behourd. As the recruits saunter away I approach, making brief eye contact. He gives me a look of relief and longing, but it is replaced in a fash. He's afraid. I realise we're not alone. black clad figures close in. We're both beaten to the ground, hooded and dragged to a nearby building.

Shaya was here in Eysenlaan. I could no more sneak past her undetected than a freshly roasted chicken could escape the attention of a hungry dog. She still smoulders. I know I won't die here, tied to a wooden post surrounded by Shaya's baying minions. But father thinks I will, he cries at Shaya to take his life and spare mine. Shaya sees how this plee is a hammer-blow to my spirit. She smiles at father. She places a curse on father. He begins to sweat. The sweat starts to boil off his skin and moments later he is on fire. He tries to supress his own cries but the pain of magical immolation would cause even a witcher to scream. I tried to close my eyes but Shaya locked them open with the wave of a hand. Father shriveled, then turned to ash. His dying heat set his chair on fire and burned our binding ropes. Shaya's minions move to put the fire out, they were unaware that my own binding ropes had loosened. 

Shaya tells me that she still loves me and is willing to give me a second chance. Only now do I realise the depths of her insanity. She raises her hand as if to repeat her burning curse. The world seems to slow down. I watch myself dive a hand into my father's piled ashes. My hand burns in agony as it grasps my fathers burning hot dagger. Its blade cuts through the air in a broad sweep that cuts through Shaya's outstretched hand. Three fingers drop to the floor. Magical energies are already flowing but their direction is now blocked. The room shakes and the minions dive for cover. I make my escape, father's dagger is welded to my palm.

I don't stop running until I'm south of the Yaruga. On the edge of the Fiery mountains I encounter a group of dwarven miners take pity on me and help me recover. The scar on my right is perminent but I quickly adapt to it's tightness. The vision of my world burning no longer haunts by nights, instead I see father, burning. I return to my life as a bodyguard and mercenary. My first job is the accompany my dwarven companions to Mahakam. I gain the moniker "Betty Blackheart". I'm withdrawn and a little prickly but I initially bristle at the name, but I find that it keeps people away, which is good. Knowing that Shaya is likely out there and hungry for revenge keeps me alert.



* *1263* +
First Northern War. The sacking of Cintra. Geralt reunited with his child of surprise.

* *1267* +
Secret pact between the northern kings at Hagge castle. Betrayal at Thanedd.

* *1268* +

** The Battle of Brenna. I'm pressed into the service of Foltest, initially as a scout, then during the battle I fought as part of the voluteer group on the banks of the Chotla, against which Menno Coehorn made his final fateful charge.

** The lodge of sorceresses (woman only) The forces of Nilfgaard invade Aedirn.
**  Conquest of Lyria, Conquest of Rivia, Battle of Alderberg, Sack of Vengerberg, SUrrender of Verden. Seack of Brugge, Siege of Dillingen, Battle of Chotla...

** Nilfgaard's East Army Group, led by Ardal Aep Dahy tasked with securing Lyria, Rivia and Aedirn

** Year ends with the Peace of Cintra. Nilfgaard loses all its lands north of the Yaruga.

** Aedirn lays in a state of ruin. 80% of Vengerburg burned to ashes. 

I continue to operate as a scout in the area surrounding Brena and Maribor.

* *1270* I acquire an exquisite bow, created by the master bow maker Geimdath, whose life I saved after he was accosted during the recent purge of no-humans.

* *1271* Play begins

* After Foltest's assasination Temeria's irregular forces fall apart. For a while I continue to work as a messenger and scout between Maribor and Vyzima.

