=== Lizbetta of Eyselaan

Born in 1240

* *1251* + 
My happiest memories are also my earliest. I was a cheerful youngling, unruly and hellbent from the call of the grandad's cockells till the fall of the star-filled vail. Father practically egged-on my bad behavior. He was the chief bodyguard of Count Viston Lauretton-de-Truane, a demanding job that often felt like a gaol sentence. I think seeing me living a life of complete freedom sated his own hunger for a carefree life.
+
When he saw me playing with a sword he was at first amused, non of my elder brothers had taken any interest in the soldiering arts, but his ammusement soon turned into a kind of pridefull glee. "Betty, you've some fire in your belly, unlike your brothers. If you work hard, I'll teach you how to fight. Just don't tell your mother!"
+
He taught me well. Maybe too well. 

* *1255* + 
Father accompanied Count Viston on a mission to Kaedwen, under the direct order of King Videmont. It would be an endless run of peacetalks and diplomatic horsetrading. Father convinced mother that the long trip would be dull but safe trip so the whole family went along as part of the Lauretton-de-Truane entourage.
